#!/usr/bin/env zsh

source stowdirs

DOT_FILES=$HOME/.dotfiles

pushd $DOT_FILES
for folder in $(echo $STOW_TO_HOME | sed "s/,/ /g")
do
  echo "Removing $folder from ~"
  stow -D $folder
done

for folder in $(echo $STOW_TO_DOTCONFIG | sed "s/,/ /g")
do
  echo "Removing $folder from ~/.config"
  stow -D $folder
done
popd

